name: 标记重复的问题
on:
  issues:
    types: [closed]

permissions:
  issues: write

jobs:
  label_duplicate_issue:
    if: github.event.issue.state_reason == 'duplicate'
    runs-on: ubuntu-latest
    steps:
      - name: Label duplicate issue
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          ${{github.event.issue.url}}/labels \
          --data '{"labels":["重复"]}'
      - name: Get duplicate issue number
        run: |
          duplicate_issue_number=$(curl ${{github.event.issue.html_url}} | 
          grep react-app.embeddedData | sed -e 's/<script[^>]*>//' | 
          sed 's/<\/script>//' |
          jq '.payload.preloadedQueries[0].result.data.repository.issue.duplicateOf.number')
          echo "duplicate_issue_number=$duplicate_issue_number" >> $GITHUB_ENV
      - name: Add comment to issue
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          ${{github.event.issue.url}}/comments \
          -d '{"body":"与 #${{env.duplicate_issue_number}}" 重复"}'