name: 标记重复的问题
on:
  issues:
    types: [closed]

jobs:
  label_duplicate_issue:
    if: github.event.issue.state_reason == 'duplicate'
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          ${{github.event.url}}/labels \
          --data '{"labels":["重复"]}'